### ISSUE TITLE
Jest can't be found after upgrading to version 0.4.74 with nx project with buildable libraries

### ISSUE THREAD

**Issue by ctunon-align** [firsttris/vscode-jest-runner#387]
Hello.

After upgrading to version >=0.4.75 of the extension, we started getting the following error:
```
 '/libs/domains/shared/ui/[REDACTED]/node_modules/jest/bin/jest.js' '/libs/domains/shared/ui/[REDACTED]/src/lib/[REDACTED]/[REDACTED].component.spec.ts' -c '/libs/domains/shared/ui/[REDACTED]/jest.config.ts' -t '[REDACTED]'
node:internal/modules/cjs/loader:1247
  throw err;
  ^

Error: Cannot find module '/libs/domains/shared/ui/[REDACTED]/node_modules/jest/bin/jest.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
    at Function._load (node:internal/modules/cjs/loader:1070:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

We have nx setup with buildable libraries. Each buildable library will have their own package.json but the node_module directory is at the root.
Our structure looks similar to this

```
/ 
-- libs
---- lib1
------- package.json
---- lib2
------- package.json
-- package.json
-- node_modules
```
On version <=0.4.74 the extension was working in our setup.
This might be the change that caused our issue:
https://github.com/firsttris/vscode-jest-runner/commit/57a33d27b13e4c760f62192b7939b22dac7bc661

**Comment by firsttris** [comment]
Hey thanks for reporting i reverted this commit. let me know if this fixes the issue for you

**Comment by firsttris** [comment]
should be fixed in 0.4.76

**Comment by ctunon-align** [comment]
working in 0.4.77. Thanks for the quick response :)
